### ISSUE TITLE
Will it work on iOS6?

### ISSUE THREAD

**Issue by garudaonekh** [Ciechan/BCMeshTransformView#2]
Hi,
very Interesting animation. Will it work on ios6 also? 

Thanks;

**Comment by Ciechan** [comment]
In its present form it doesn't as it makes use of iOS7 specific APIs. In theory you could replace this line of `BCMeshTexture.m` file:

```
[view drawViewHierarchyInRect:view.layer.bounds afterScreenUpdates:NO];
```

with that one:

```
[view.layer renderInContext:context];
```

I'm not 100% sure, but I think this is the only iOS7 call in the project and replacing the mentioned line should work.

**Comment by pcjbird** [comment]
It works fine use
   <pre><code> [view.layer renderInContext:context];</code></pre>
or
   <pre><code>[view.layer.presentationLayer renderInContext:context];</code></pre>

However, in iOS6 or before, label or other control's background seems to be white default. As a result, if you want to show the container's background color, you should set the background color of all the subviews to be [UIColor clearColor].
