### ISSUE TITLE
Render Transform View Hierarchy Offscreen

### ISSUE THREAD

**Issue by mmobarak** [Ciechan/BCMeshTransformView#4]
Hi,

I'm trying to use BCMeshTransformView to obtain a modified UIImage from an existing UIImage. My code looks like this:

```
- (UIImage *)addSmile:(UIImage *)inputImage {
    float scale = inputImage.scale;
    CGRect imageRect =  CGRectMake(0.f, 0.f, inputImage.size.width, inputImage.size.height );

    UIImageView *imageView = [[UIImageView alloc] initWithImage:inputImage];

    BCMeshTransformView *transformView = [[BCMeshTransformView alloc] initWithFrame:imageRect];
    transformView.autoresizingMask = UIViewAutoresizingFlexibleHeight | UIViewAutoresizingFlexibleWidth;
    transformView.diffuseLightFactor = 0.0;
    transformView.meshTransform = [BCMutableMeshTransform buldgeMeshTransformAtPoint:CGPointMake(100, 100) withRadius:120.0 boundsSize:transformView.bounds.size];
    [transformView.contentView addSubview:imageView];

    UIView *containerView = [[UIView alloc] initWithFrame:imageRect];
    [containerView addSubview:transformView];

    UIGraphicsBeginImageContextWithOptions(workingImage.size, YES, scale);
      [containerView.layer renderInContext:UIGraphicsGetCurrentContext()];
      UIImage *outputImage = UIGraphicsGetImageFromCurrentImageContext();
    UIGraphicsEndImageContext();

    return outputImage;
}
```

When the references to the BCMeshTransformView are removed, outputImage is a copy of inputImage as expected. With the code above, outputImage is just a black rectangle with teh dimensions of inputImage. 

Is BCMeshTransformView supposed to work in an offscreen context, or should I use a different approach to obtain a transformed UIImage?

Thanks very much!

**Comment by Ciechan** [comment]
BCMeshTransformView uses OpenGL to do its rendering which means it uses `CAEAGLLayer` as its rendering layer. Apparently this layer is not renderable in context which kind of makes sense, as `renderInContext:` rasterization happens on the CPU, while OpenGL is pure GPU.

However, BCMeshTransformView uses `GLKView` as its rendering view, and this class has a convenient [`- snapshot`](https://developer.apple.com/library/ios/documentation/glkit/reference/glkview_classreference/Reference/Reference.html#//apple_ref/occ/instm/GLKView/snapshot) method. You can move the following line from the .m file to the .h file:

```
@property (nonatomic, strong) GLKView *glkView;
```

Then simply call:

```
UIImage *image = [transformView.glkView snapshot];
```

I'm not entirely sure if this will all work out of the box (rendering timing could be an issue here), but it's worth trying.

You could also try the new iOS7 rasterisation call which seems to be performed on the GPU:

```
- (BOOL)drawViewHierarchyInRect:(CGRect)rect afterScreenUpdates:(BOOL)afterUpdates;
```

Replace the `renderInContext:` call with this one to test it.

**Comment by mmobarak** [comment]
Thanks for the quick reply! I've exposed the glkView as suggested and tried the following, but unfortunately without success:

```
    UIGraphicsBeginImageContextWithOptions(inputImage.size, YES, scale);
    [containerView drawViewHierarchyInRect:imageRect afterScreenUpdates:NO];
    outputImage = [transformView.glkView snapshot];
    UIGraphicsEndImageContext();
```

outputImage now seems to be a transparent image with the dimensions of inputImage. I'm not certain what you mean regarding potential timing issues, but I tried inserting a sleep(1) just before accessing the snapshot and saw no difference. Any further guidance would be appreciated.

**Comment by Ciechan** [comment]
Does adding `[transformView.glkView.layer displayIfNeeded];` before the `snapshot` call help?

**Comment by mmobarak** [comment]
I'm afraid it doesn't. I'm running my effects in a background thread and thought that might be a problem, but now running on the main thread and still seeing the same result.

**Comment by Ciechan** [comment]
I hacked on the code a little bit and managed to get it to work. It's not perfect as I had to add a completion block, because I'm snapshotting the view on the next tick on of the run loop.

```
- (void)addSmile:(UIImage *)inputImage withCompletionBlock:(void (^)(UIImage *))completion
{
    float scale = inputImage.scale;
    CGRect imageRect =  CGRectMake(0.f, 0.f, inputImage.size.width, inputImage.size.height );

    UIImageView *imageView = [[UIImageView alloc] initWithImage:inputImage];

    BCMeshTransformView *transformView = [[BCMeshTransformView alloc] initWithFrame:imageRect];
    transformView.autoresizingMask = UIViewAutoresizingFlexibleHeight | UIViewAutoresizingFlexibleWidth;
    transformView.diffuseLightFactor = 0.0;
    transformView.meshTransform = [BCMutableMeshTransform buldgeMeshTransformAtPoint:CGPointMake(100, 100) withRadius:120.0 boundsSize:transformView.bounds.size];
    [transformView.contentView addSubview:imageView];

    UIView *containerView = [[UIView alloc] initWithFrame:CGRectZero];
    [containerView addSubview:transformView];

    [self.window addSubview:containerView];

    dispatch_after(dispatch_time(DISPATCH_TIME_NOW, (int64_t)(0 * NSEC_PER_SEC)), dispatch_get_main_queue(), ^{
        UIImage *snapshot = [(GLKView *)[transformView valueForKey:@"glkView"] snapshot];

        [containerView removeFromSuperview];

        completion(snapshot);
    });
}
```

Apparently a view has to be in a window view hierarchy for CoreAnimation to work correctly, but I'm setting the frame of `container` view to `CGRectZero` and it won't be visible on screen. I'm sorry for the code quality, but I don't really have much time to work on this more.

**Comment by mmobarak** [comment]
Thank you! I'll give this a spin tomorrow morning and let you know how it goes.

**Comment by mmobarak** [comment]
Got this strategy working. Thanks very much for your help!

**Comment by ArvindRajpurohit81** [comment]
Ciechan ,dude i am not able to integrate your bctransform library in my project  through xcode6.0.
i want to make pinch distortion instead of budge, plz can u help me out how to integrate in simple steps without pod 
my mail id arvin8192@gmail.com
