### ISSUE TITLE
Mesh translation

### ISSUE THREAD

**Issue by JPluto** [Ciechan/BCMeshTransformView#5]
Hi,
How to achieve pixel translation

**Comment by Ciechan** [comment]
Do you mean translating a mesh by fixed amount of points in horizontal/vertical direction? You have to convert from unit coordinate back to points coordinates:

Assuming your view is 300x400 points then to move it by 1 pixel to the right and down you'd have to translate the mesh by `1.0/300.0` in `x` direction and by `1.0/400.0` in `y` direction.
