### ISSUE TITLE
iOS 8 support

### ISSUE THREAD

**Issue by eskewj** [Ciechan/BCMeshTransformView#6]
Does not appear to compile in xcode 6.  Will there be an update?

**Comment by Ciechan** [comment]
Have you checked out the latest version? This problem should've been fixed [by this commit](https://github.com/Ciechan/BCMeshTransformView/commit/4223c28fdb1a9d17765c1ee888da5f51b984cfdd). Is it some other issue?

**Comment by eskewj** [comment]
Yes, this fixed it.  Oversight on my part.  Thank you!

**Comment by eskewj** [comment]
Closing issue.
