### ISSUE TITLE
Circular Reference To BCMeshTransformView

### ISSUE THREAD

**Issue by mmobarak** [Ciechan/BCMeshTransformView#9]
It looks like the following line in BCMeshTransformView::CommonInit causes _display_link to hold a reference to the containing BCMeshTransformView. As a result, the transform view is never deallocated. 

```
_displayLink = [CADisplayLink displayLinkWithTarget:self selector:@selector(displayLinkTick:)];
```

I'm temporarily working around this by exposing a method that allows me to call:

```
[_display_link invalidate]
```

when I'm done with the transform view. It is then deallocated when I'm done referencing it. 

If there's a better way to handle this, please make a suggestion and I'll code it up and open a pull request.

Thanks again for this very useful project.

**Comment by mmobarak** [comment]
FWIW, here's my fork with the minor change I made: 

https://github.com/mmobarak/BCMeshTransformView/tree/7f49bab5980128987ff4b0d7ad0669567c94baea

Oddly, this change works fine on an actual device, but the leak still occurs on the XCode Simulator, as of 5.1.1.

**Comment by Ciechan** [comment]
Wow, I can't believe I've missed this, it's been leaking so much memory... Thank you very much for noticing this! I pushed a slightly different fix that removes the retain cycle and doesn't require invalidation call.

Once again, big thanks for finding this!

**Comment by mmobarak** [comment]
Works great now, thanks!
